-- Building blocks:

-- Joins

=-- Find the total revenue generated by each product and list the top 3 products by revenue.
/*
CREATE TABLE Products_q1 (
    ProductID INT PRIMARY KEY,
    ProductName VARCHAR(100),
    Price DECIMAL(10, 2)
);

CREATE TABLE Sales_q1 (
    SaleID INT PRIMARY KEY,
    ProductID INT,
    Quantity INT,
    SaleDate DATE,
    FOREIGN KEY (ProductID) REFERENCES Products_q1(ProductID)
);

INSERT INTO Products_q1 (ProductID, ProductName, Price)
VALUES 
(1, 'Laptop', 800.00),
(2, 'Mouse', 25.00),
(3, 'Keyboard', 45.00),
(4, 'Monitor', 200.00),
(5, 'Headphones', 150.00);

INSERT INTO Sales_q1 (SaleID, ProductID, Quantity, SaleDate)
VALUES 
(1, 1, 3, '2024-01-10'),
(2, 2, 10, '2024-01-15'),
(3, 3, 5, '2024-01-20'),
(4, 4, 2, '2024-01-25'),
(5, 5, 4, '2024-02-01'),
(6, 1, 2, '2024-02-05'),
(7, 3, 3, '2024-02-10');
*/

-- Select * from products_q1
-- Select * from sales_q1

With Cte as
(
Select p.productID, p.productName,
p.price ,
s.quantity
from Products_q1 as p
left join
Sales_q1 as s
on 
p.ProductID = s.ProductID

)

Select 
productID, productName,
sum(price * quantity) as total_revenue
from cte
group by productID, productName
order by sum(price * quantity) desc;



-- 2. Subquery
-- Find employees whose salaries are greater than average salaries in their department
/*
CREATE TABLE Employees_sq (
    EmployeeID INT PRIMARY KEY,
    EmployeeName VARCHAR(100),
    DepartmentID INT,
    Salary DECIMAL(10, 2)
);

CREATE TABLE Departments_sq (
    DepartmentID INT PRIMARY KEY,
    DepartmentName VARCHAR(100)
);

INSERT INTO Departments_sq (DepartmentID, DepartmentName)
VALUES 
(1, 'HR'),
(2, 'Engineering'),
(3, 'Sales');

INSERT INTO Employees_sq (EmployeeID, EmployeeName, DepartmentID, Salary)
VALUES 
(1, 'Alice', 1, 60000.00),
(2, 'Bob', 2, 120000.00),
(3, 'Charlie', 2, 100000.00),
(4, 'David', 3, 80000.00),
(5, 'Eve', 3, 75000.00),
(6, 'Frank', 1, 55000.00);
*/

Select * from employees_sq
Select * from departments_sq

SELECT 
    e.EmployeeName,
    e.Salary,
    d.DepartmentName
FROM 
    Employees_sq e
JOIN 
    Departments_sq d
ON 
    e.DepartmentID = d.DepartmentID
WHERE 
    e.Salary > (
        SELECT 
            AVG(Salary)
        FROM 
            Employees_sq
        WHERE 
            DepartmentID = e.DepartmentID
    );


-- 3. CTE

